name: Pull Request Tests

on:
  pull_request:
    branches: [develop]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Ajustar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar pnpm
        run: npm install -g pnpm

      - name: Instalar dependências
        run: pnpm install

      - name: Definir variáveis de ambiente
        run: |
          echo "APP_KEYS=${{ secrets.APP_KEYS }}" >> .env
          echo "API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }}" >> .env
          echo "ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }}" >> .env
          echo "TRANSFER_TOKEN_SALT=${{ secrets.TRANSFER_TOKEN_SALT }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "DATABASE_FILENAME=${{ secrets.DATABASE_FILENAME }}" >> .env

      - name: Constroi o Strapi
        run: pnpm build

      - name: Iniciar o Strapi
        env:
          HOST: 0.0.0.0
          PORT: 1337
        run: |
          pnpm develop &
          n=0
          until curl --fail http://localhost:1337; do
            n=$((n+1))
            if [ $n -ge 60 ]; then
              echo "Strapi não iniciou no tempo esperado" && exit 1
            fi
            sleep 5
          done

      - name: Instalar Playwright e dependências
        run: pnpm exec playwright install --with-deps

      - name: Executar testes E2E com Playwright
        run: pnpm exec playwright test
